### ISSUE TITLE
Generating from existing pdf and into buffer?

### ISSUE THREAD

**Issue by alpfactory-alex** [Rogerrrrrrrs/SwissQRBill#91]
Very cool library thanks @Rogerrrrrrrs for creating this. I've got a question though:

1. Is it possible to generate into a buffer instead of a file?
2. Is it possible to generate based on an existing pdf that gets loaded instead of creating a new one?
3. Will the addQRBill automatically discover if there's enough space left on current pdf and attach to new page if not?

**Comment by Rogerrrrrrrs** [comment]
Thank you @alpfactory-alex 

1. Not yet, but I am currently working on browser support which works with buffers. I can also add this functionality for node.
2. At the moment, this is not possible because the underlaying PDFKit does not support this feature. You could use SwissQRBill to only generate the QR Part and use a third party module to merge the two PDF files. To keep this library as lightweight as possible, I would rather not inegrate this approach into the library.
3. Yes, the addQRBill checks if enough space is left on the current page, otherwise it will add a new page in the size of A6/5 which is only the QR part.

**Comment by alpfactory-alex** [comment]
@Rogerrrrrrrs Yeah I just tried your browser implementation really cool. Though I am wrapping it myself now to support browser-blob stream on browser and regular streams running within jest so its the best of both worlds :)

any idea when you'll push the browser based implementation on npmjs?

may I ask your initial reason for creating this library?

**Comment by alpfactory-alex** [comment]
What I mean is that your generic class now actually is exactly what I was looking for (in your browser branch):

```
import * as SwissQRBill from 'swissqrbill/lib/swissqrbill'

const pdf = new SwissQRBill.PDF(data, {
        size: 'A4',
        autoGenerate: false,
    })

// do some more work here

pdf.end()

const file = require('fs').createWriteStream('./test.pdf')
    const stream = pdf.pipe(file)

    stream.on('finish', ev => {
        console.log('DONE!!!')
        pdf.emit('finish', ev)
        done()
    })
```

doing so we have full control over it. Will it stay this way? Its perfect ;)

**Comment by Rogerrrrrrrs** [comment]
> Will it stay this way? Its perfect ;)

I did not actually spend much time for browser support yet, and I don't think my implementation does work yet. But the splitted approach with a generic class will stay.

> any idea when you'll push the browser based implementation on npmjs?

Probably within the next 2 weeks.

> may I ask your initial reason for creating this library?

I needed a way to autogenerate bills based of online orders, so the new QR bill came just in time :)

**Comment by alpfactory-alex** [comment]
Cool. I tried it and it actually seems to work fine so far.

By enabling to directly use your main class I think it might even not be necessary to provide dedicated implementations for node and browser as everyone could simply provide a stream implementation to pipe into.

Eager to see it released if you need any help let me know happy to help out!

**Comment by Rogerrrrrrrs** [comment]
@alpfactory-alex I have updated the [experimental-browser-support](https://github.com/Rogerrrrrrrs/SwissQRBill/tree/experimental-browser-support) branch. Now everything should be properly bundled and ready to use in browser.

> By enabling to directly use your main class I think it might even not be necessary to provide dedicated implementations for node and browser as everyone could simply provide a stream implementation to pipe into.

This is true, but I want this library to be as easy to use as possible and I also want to avoid breaking API changes.

With my updated code you can either pass the output path as before or you can pass a writeable stream. This way you should be able to achieve to same result without having to access the generic class directly (even though you can still do this) and while still having not too much API changes.

I have created a working browser example which should be pretty easy to use: https://github.com/Rogerrrrrrrs/SwissQRBill-browser-example/blob/master/src/index.ts

Please let me know what you think :)

**Comment by alpfactory-alex** [comment]
Its really good thanks :) Now it just need to be on NPM ;-)) Though it is now bundling everything together including pdf-kit into the browser module right? I think there should be a regular, lightweight es6 module too no? As we, for example, already use pdf-kit and as of now with this build tree shaking would be extremely hard.

**Comment by alpfactory-alex** [comment]
Ok I think looking at the transpiled code here: https://github.com/Rogerrrrrrrs/SwissQRBill/blob/experimental-browser-support/lib/swissqrbill.js we could simply use this one instead of the browser one to get proper tree shaking :)

**Comment by Rogerrrrrrrs** [comment]
That's right, only browser.js is bundled. If you want to do the bundling and stream handling yourself, I think it is best to just use `lib/swissqrbill` directly. This way I can provide an easy to use way while the more advanced users can still do their own thing.

I will release the new version this evening on npm.

**Comment by Rogerrrrrrrs** [comment]
SwissQRBill v2.0.0 is now released on npm
